// backend/controllers/submissionController.js
import { GoogleGenAI } from '@google/genai';
import pkg from 'pg';
import nodemailer from 'nodemailer';
const { Pool } = pkg;

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const ai = process.env.GEMINI_API_KEY ? new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY }) : null;

// --- Nodemailer Setup ---
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS, // Your App Password
    },
});

// --- Main Webhook Handler ---
export const handleGoogleFormWebhook = async (req, res) => {
    const { studentEmail, generatedWorksheetId, answers } = req.body;

    if (!studentEmail || !generatedWorksheetId || !answers) {
        return res.status(400).send('Missing required fields.');
    }

    try {
        // 1. Find the student by email
        const studentRes = await pool.query('SELECT id FROM students WHERE email = $1', [studentEmail]);
        if (studentRes.rows.length === 0) {
            console.error(`Submission from unknown student email: ${studentEmail}`);
            return res.status(404).send('Student not found.');
        }
        const studentId = studentRes.rows[0].id;

        // 2. Save the initial submission
        const answersText = Object.values(answers).join('\n\n---\n\n');
        const submissionRes = await pool.query(
            `INSERT INTO worksheet_submissions (student_id, generated_worksheet_id, student_answers_raw)
             VALUES ($1, $2, $3)
             ON CONFLICT (student_id, generated_worksheet_id) DO UPDATE SET student_answers_raw = EXCLUDED.student_answers_raw, submitted_at = NOW()
             RETURNING id`,
            [studentId, generatedWorksheetId, answersText]
        );
        const submissionId = submissionRes.rows[0].id;

        // 3. Trigger the full processing asynchronously (don't make Google wait)
        processSubmission(submissionId);

        // 4. Immediately tell Google "we got it"
        res.status(200).send('Submission received and is being processed.');

    } catch (error) {
        console.error('Error in webhook handler:', error);
        res.status(500).send('Internal server error.');
    }
};

// --- Asynchronous Processing Function ---
async function processSubmission(submissionId) {
    try {
        const submissionData = await pool.query('SELECT student_answers_raw FROM worksheet_submissions WHERE id = $1', [submissionId]);
        const answersText = submissionData.rows[0].student_answers_raw;

        // 1. AI Content Detection
        let aiDetectionResult = { is_likely_ai_generated: null, details: 'Detection failed.' };
        try {
            const detectionPrompt = `Analyze the following text and determine the likelihood that it was generated by an AI. Provide a simple JSON response: {"is_likely_ai_generated": boolean, "confidence_score": float between 0 and 1, "reasoning": "brief explanation"}\n\nText to analyze:\n${answersText}`;
            const detectionResponse = await ai.models.generateContent({ model: "gemini-2.5-flash", contents: detectionPrompt });
            let rawJsonResponse = detectionResponse.text.trim().replace(/```json\n?|\n?```/g, '');
            const parsedResponse = JSON.parse(rawJsonResponse);
            aiDetectionResult = {
                is_likely_ai_generated: parsedResponse.is_likely_ai_generated ?? null,
                details: `Confidence: ${parsedResponse.confidence_score?.toFixed(2)}. Reasoning: ${parsedResponse.reasoning}`
            };
        } catch (e) { console.error('AI detection parsing failed:', e); }

        await pool.query(
            'UPDATE worksheet_submissions SET is_likely_ai_generated = $1, ai_detection_details = $2 WHERE id = $3',
            [aiDetectionResult.is_likely_ai_generated, aiDetectionResult.details, submissionId]
        );

        // 2. AI Evaluation
        const evalData = await getEvaluationContext(submissionId);
        const evaluationPrompt = createEvaluationPrompt(evalData, aiDetectionResult);
        const evalResponse = await ai.models.generateContent({ model: "gemini-2.5-flash", contents: evaluationPrompt });
        const evaluationDetails = evalResponse.text.trim();

        let assignedMarks = "Evaluation Complete";
        const scoreMatch = evaluationDetails.match(/Total Score:\s*(\d+(\.\d+)?\s*\/\s*\d+)/i);
        if (scoreMatch) assignedMarks = scoreMatch[1];
        
        await pool.query(
            'UPDATE worksheet_submissions SET ai_evaluation_details = $1, ai_assigned_marks = $2 WHERE id = $3',
            [evaluationDetails, assignedMarks, submissionId]
        );

        // 3. Send Feedback Email
        await sendFeedbackEmail(submissionId);

    } catch (error) {
        console.error(`Processing failed for submission ${submissionId}:`, error);
        await pool.query(
            `UPDATE worksheet_submissions SET ai_evaluation_details = $1, ai_assigned_marks = 'Error' WHERE id = $2`,
            [`Evaluation failed: ${error.message}`, submissionId]
        );
    }
}

// --- Helper Functions ---

async function getEvaluationContext(submissionId) {
    const result = await pool.query(`
        SELECT ws.student_answers_raw, gw.worksheet_content, gw.answer_key_content, ch.chapter_name, sub.subject_name, s.email as student_email
        FROM worksheet_submissions ws
        JOIN generated_worksheets gw ON ws.generated_worksheet_id = gw.id
        JOIN chapters ch ON gw.chapter_id = ch.id
        JOIN subjects sub ON ch.subject_id = sub.id
        JOIN students s ON ws.student_id = s.id
        WHERE ws.id = $1
    `, [submissionId]);
    return result.rows[0];
}

function createEvaluationPrompt(data, detectionResult) {
    let aiCheckInfo = `AI Content Check: ${detectionResult.details}`;
    
    return `
        Act as a helpful ${data.subject_name} teacher evaluating a student's worksheet submission for the chapter "${data.chapter_name}".

        Original Questions:
        ${data.worksheet_content}

        Correct Answer Key:
        ${data.answer_key_content}

        Student's Submitted Answers:
        ${data.student_answers_raw}

        ${aiCheckInfo}

        Please evaluate the student's answers based on the answer key. For each question:
        1. Briefly state if the answer is correct, partially correct, or incorrect.
        2. Provide concise feedback explaining why.

        Finally, provide a "Total Score" (e.g., "Total Score: 8/10") and "Overall Remarks" summarizing performance. If the content check indicated AI generation, you may add a brief, non-accusatory note encouraging original work.
        Format your response clearly.
    `;
}

async function sendFeedbackEmail(submissionId) {
    const data = await getEvaluationContext(submissionId);
    const evalResult = await pool.query('SELECT ai_assigned_marks, ai_evaluation_details FROM worksheet_submissions WHERE id = $1', [submissionId]);
    const { ai_assigned_marks, ai_evaluation_details } = evalResult.rows[0];

    const mailOptions = {
        from: `"Sahayak App" <${process.env.EMAIL_USER}>`,
        to: data.student_email,
        subject: `Feedback for your worksheet on "${data.chapter_name}"`,
        text: `Hello,\n\nHere is the feedback for your recent submission.\n\nScore: ${ai_assigned_marks}\n\n--- Detailed Feedback ---\n${ai_evaluation_details}\n\nRegards,\nSahayak Platform`,
        html: `<p>Hello,</p><p>Here is the feedback for your recent submission.</p><p><b>Score: ${ai_assigned_marks}</b></p><hr><p><b>Detailed Feedback:</b></p><pre>${ai_evaluation_details}</pre><hr><p>Regards,<br>Sahayak Platform</p>`,
    };

    try {
        await transporter.sendMail(mailOptions);
        await pool.query('UPDATE worksheet_submissions SET feedback_sent_to_student_at = NOW() WHERE id = $1', [submissionId]);
        console.log(`Feedback email sent for submission ${submissionId}`);
    } catch (error) {
        console.error(`Failed to send feedback email for submission ${submissionId}:`, error);
    }
}

// --- Teacher-Facing API Function ---
export const getSubmissionsForChapter = async (req, res) => {
    const { teacherAssignmentId, chapterId } = req.params;
    const teacherId = req.user.id;

    try {
        // Security check: Does this teacher own this assignment?
        const ownerCheck = await pool.query('SELECT 1 FROM teacher_class_assignments WHERE id = $1 AND teacher_id = $2', [teacherAssignmentId, teacherId]);
        if (ownerCheck.rows.length === 0) return res.status(403).json({ message: 'Access denied' });

        const query = `
            SELECT 
                s.name as student_name,
                s.roll_number,
                ws.id as submission_id,
                ws.submitted_at,
                ws.ai_assigned_marks,
                ws.is_likely_ai_generated
            FROM student_class_enrollments sce
            JOIN students s ON sce.student_id = s.id
            JOIN teacher_class_assignments tca ON sce.section_id = tca.section_id
            LEFT JOIN generated_worksheets gw ON tca.id = gw.teacher_assignment_id AND gw.chapter_id = $2
            LEFT JOIN worksheet_submissions ws ON s.id = ws.student_id AND gw.id = ws.generated_worksheet_id
            WHERE tca.id = $1
            ORDER BY s.roll_number;
        `;
        const { rows } = await pool.query(query, [teacherAssignmentId, chapterId]);
        res.json(rows);
    } catch (error) {
        console.error('Error getting submissions for chapter:', error);
        res.status(500).json({ message: 'Server error' });
    }
};